### PR TITLE
CSV column Separator parameter

### LINKED ISSUE #9: Override CSV Column Separator
**Is your feature request related to a problem? Please describe.**
When you export as CSV it always export as semicolon separataed values while some programs may not want this format and want to override it with comma separated values.

**Describe the solution you'd like**
It would be good to provide an option for CSV type to include cell separator.

**Describe alternatives you've considered**
We take the data out and run a manual process on it to replace all semicolons with comma but that is not ideal

**Additional context**
None

### PR DESCRIPTION
**Pull request by farrukhsubhani**
Please check this and anything else required as I am editing all on github so there can be mistake or missing code.
Thanks for all the help.
This should close #9

### CODE REVIEW

**Comment by gharibi** [comment]
There is a small problem with the default `params` in [HERE](https://github.com/gharibi/JsObjExporter/blob/66ef3d5998fb19c196a9f2b803596f4cd67029b5/src/js/init.js#L22).

Your default is `ColumnSeparator` whereas it should be `columnSeparator`. Could you please refactor it and open the PR again? thanks.

**Comment by farrukhsubhani** [comment]
Thanks, it was my phone capitalised first letter and i did not notice.

**Comment by farrukhsubhani** [comment]
Thanks for all your help, just wanted to make sure that:

1. Headers if present should also use same separator
2. Dont forget to send changes to minified file

Let me know if there is anything I can do to help with.

**Comment by gharibi** [comment]
Great, thanks. Sure, I will check and do it tonight.

**Pull request merged**
